services:
  traffic_manager:
    image: stopwatch_traffic_manager
    ports:
     - 80:80
  front_end:
    image: stopwatch_front_end
  back_end:
    image: stopwatch_back_end
    working_dir: /home/node/back_end
    command: "npm start"
    volumes:
      - ./data:/home/node/back_end/data